.srv/docker/redmine/redmine/plugins/redmine_contacts/config/routes.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2015 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

#custom routes for this plugin
  resources :contacts, :path_names => {:contacts_notes => 'notes'} do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :contacts_notes
      post :bulk_edit, :bulk_update, :send_mails, :preview_email
      delete :bulk_destroy
    end
    member do
      get 'tabs/:tab' => 'contacts#show', :as => "tabs"
      get 'load_tab' => 'contacts#load_tab', :as => "load_tab"
    end
    resources :contacts_projects, :path => "projects", :only => [:new, :create, :destroy]
  end

  resources :projects do
    resources :contacts, :path_names => {:contacts_notes => 'notes'} do
      collection do
        get :contacts_notes
      end
    end

  end

  resources :projects do
    resources :crm_queries, :only => [:new, :create]
  end

  resources :crm_queries, :except => [:show]

  resources :notes

  match '/contacts_tags', :controller => 'contacts_tags', :action => 'destroy', :via => :delete

  resources :contacts_tags do
    collection do
      post :merge, :context_menucha
      get :context_menu, :merge
    end
  end

  match 'projects/:project_id/contacts/:contact_id/new_task' => 'contacts_issues#new', :via => :post

  match 'contacts/:contact_id/duplicates' => 'contacts_duplicates#index', :via => [:get, :post]

  match 'projects/:project_id/deal_categories/new' => 'deal_categories#new', :via => [:get, :post]


  match 'auto_completes/taggable_tags' => 'auto_completes#taggable_tags', :via => :get, :as => 'auto_complete_taggable_tags'
  match 'auto_completes/contact_tags' => 'auto_completes#contact_tags', :via => :get, :as => 'auto_complete_contact_tags'
  match 'auto_completes/contacts' => 'auto_completes#contacts', :via => :get, :as => 'auto_complete_contacts'
  match 'auto_completes/companies' => 'auto_completes#companies', :via => :get, :as => 'auto_complete_companies'

  match 'users/new_from_contact/:id' => 'users#new_from_contact', :via => :get
  match 'contacts_duplicates/:action' => 'contacts_duplicates', :via => [:get, :post]
  match 'contacts_duplicates/search' => 'contacts_duplicates#search', :via => :get, :as => 'contacts_duplicates_search'
  match 'contacts_issues/:action' => 'contacts_issues', :via => [:get, :post, :delete, :put]
  match 'contacts_vcf/:action' => 'contacts_vcf', :via => [:get, :post]
  match 'deal_contacts/:action' => 'deal_contacts', :via => [:get, :post, :delete]
  match 'deals_tasks/:action' => 'deals_tasks', :via => [:get, :post, :put]
  match 'contacts_settings/:action' => 'contacts_settings', :via => [:get, :post]
  match 'contacts_mailer/:action' => 'contacts_mailer', :via => [:get, :post]
  match 'attachments/contacts_thumbnail/:id(/:size)', :controller => 'attachments', :action => 'contacts_thumbnail', :id => /\d+/, :via => :get

.srv/docker/redmine/redmine/plugins/redmine_contacts/app/helpers/contacts_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2015 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

module ContactsHelper

  def contact_tabs(contact)
    contact_tabs = []
    contact_tabs << {:name => 'notes', :partial => 'contacts/notes', :label => l(:label_crm_note_plural)} if contact.visible?
    contact_tabs << {:name => 'contacts', :partial => 'company_contacts', :label => l(:label_contact_plural) + (contact.company_contacts.visible.count > 0 ? " (#{contact.company_contacts.count})" : "")} if contact.is_company?
    contact_tabs
  end

  def settings_contacts_tabs
    ret = [
      {:name => 'general', :partial => 'settings/contacts/contacts_general', :label => :label_general},
      {:name => 'money', :partial => 'settings/contacts/money', :label => :label_crm_money_settings},
    ]
    ret.push({:name => 'hidden', :partial => 'settings/contacts/contacts_hidden', :label => :label_crm_contacts_hidden}) if params[:hidden]
    ret
  end

  def collection_for_visibility_select
    [[l(:label_crm_contacts_visibility_project), Contact::VISIBILITY_PROJECT],
     [l(:label_crm_contacts_visibility_public), Contact::VISIBILITY_PUBLIC],
     [l(:label_crm_contacts_visibility_private), Contact::VISIBILITY_PRIVATE]]
  end

  def contact_list_styles_for_select
    list_styles = [[l(:label_crm_list_excerpt), "list_excerpt"]]
  end

  def contacts_list_style
    list_styles = contact_list_styles_for_select.map(&:last)
    if params[:contacts_list_style].blank?
      list_style = list_styles.include?(session[:contacts_list_style]) ? session[:contacts_list_style] : RedmineContacts.default_list_style
    else
      list_style = list_styles.include?(params[:contacts_list_style]) ? params[:contacts_list_style] : RedmineContacts.default_list_style
    end
    session[:contacts_list_style] = list_style
  end

  def authorized_for_permission?(permission, project, global = false)
    User.current.allowed_to?(permission, project, :global => global)
  end

  def render_contact_projects_hierarchy(projects)
    s = ''
    project_tree(projects) do |project, level|
      s << "<ul>"
      name_prefix = (level > 0 ? ('&nbsp;' * 2 * level + '&#187; ') : '')
      s << "<li id='project_#{project.id}'>" + name_prefix + link_to_project(project)

      s += ' ' + link_to(image_tag('delete.png'),
                                 contact_contacts_project_path(@contact, :id => project.id, :project_id => @project.id),
                                 :remote => true,
                                 :method => :delete,
                                 :style => "vertical-align: middle",
                                 :class => "delete",
                                 :title => l(:button_delete)) if (projects.size > 1 && User.current.allowed_to?(:edit_contacts, project))
      s << "</li>"

      s << "</ul>"
    end
    s.html_safe
  end

  def contact_to_vcard(contact)
    return false unless ContactsSetting.vcard?

    card = Vcard::Vcard::Maker.make2 do |maker|

      maker.add_name do |name|
        name.prefix = ''
        name.given = contact.first_name.to_s
        name.family = contact.last_name.to_s
        name.additional = contact.middle_name.to_s
      end

      maker.add_addr do |addr|
        addr.preferred = true
        addr.street = contact.street1.to_s.gsub("\r\n"," ").gsub("\n"," ")
        addr.locality = contact.city.to_s
        addr.region = contact.region.to_s
        addr.postalcode = contact.postcode.to_s
        addr.country = contact.country.to_s
        addr.location = 'business'
      end

      maker.title = contact.job_title.to_s
      maker.org = contact.company.to_s
      maker.birthday = contact.birthday.to_date unless contact.birthday.blank?
      maker.add_note(contact.background.to_s.gsub("\r\n"," ").gsub("\n", ' '))

      maker.add_url(contact.website.to_s)

      contact.phones.each { |phone| maker.add_tel(phone) }
      contact.emails.each { |email| maker.add_email(email) }
    end
    avatar = contact.attachments.find_by_description('avatar')
    card = card.encode.sub("END:VCARD", "PHOTO;BASE64:" + "\n " + [File.open(avatar.diskfile).read].pack('m').to_s.gsub(/[ \n]/, '').scan(/.{1,76}/).join("\n ") + "\nEND:VCARD") if avatar && avatar.readable?

    card.to_s

  end

  def set_flash_from_bulk_contact_save(contacts, unsaved_contact_ids)
    if unsaved_contact_ids.empty?
      flash[:notice] = l(:notice_successful_update) unless contacts.empty?
    else
      flash[:error] = l(:notice_failed_to_save_contacts,
                        :count => unsaved_contact_ids.size,
                        :total => contacts.size,
                        :ids => '#' + unsaved_contact_ids.join(', #'))
    end
  end

  def render_contact_tabs(tabs)
    if tabs.any?
      render :partial => 'common/contact_tabs', :locals => {:tabs => tabs}
    else
      content_tag 'p', l(:label_no_data), :class => "nodata"
    end
  end

  def importer_link
    project_contact_imports_path
  end

  def importer_show_link(importer, project)
    project_contact_import_path(:id => importer, :project_id => project)
  end

  def importer_settings_link(importer, project)
    settings_project_contact_import_path(:id => importer, :project => project)
  end

  def importer_run_link(importer, project)
    run_project_contact_import_path(:id => importer, :project_id => project, :format => 'js')
  end

end

.srv/docker/redmine/redmine/plugins/redmine_contacts/app/views/contacts/_contact_card.html.erb
<div class="contact card">
	<table class="subject_header">
		<tr>
			<td class="avatar"><%= contact_tag(contact_card, :type => "avatar", :size => 64) %></td>
			<td class="name" style="vertical-align: top;">
				<h2><%= contact_tag(contact_card, :type => "plain") %> </h2>
				<p>
				<%= h contact_card.job_title %>
				<% if !contact_card.is_company %>
				<%= " #{l(:label_crm_at_company)} " unless (contact_card.job_title.blank? or contact_card.company.blank?) %>
  				<% if contact_card.contact_company %>
  					<%= link_to contact_card.contact_company.name, {:controller => 'contacts', :action => 'show', :project_id => contact_card.contact_company.project(@project), :id => contact_card.contact_company.id } %>
  				<% else %>
  					<%= h contact_card.company %>
  				<% end %>
				<% end %>
			  </p>

			</td>


		</tr>
		<tr>
			<td colspan="2" style="padding-left: 10px;">
	  		<% if contact_card.phones.any? %>
				  <p class="phone icon icon-phone"><%=  contact_card.phones.first %></p>
				<% end %>

				<% if contact_card.emails.any? %>
				  <p class="email icon icon-email"><%= mail_to contact_card.emails.first %></p>
				<% end %>
				<%= tag_links(contact_card.tag_list) %>
			</td>
		</tr>
	</table>
</div>

.srv/docker/redmine/redmine/plugins/redmine_contacts/app/views/contacts/_form.html.erb
<%= back_url_hidden_field_tag %>
<%= error_messages_for 'contact' %>
<div class = "box tabular" id="contact_data">

<script type="text/javascript" charset="utf-8">
	function togglePerson(element) {
		if (element.checked) {
		  $('#person_data').hide();
		  $('#job_title label').get(0).innerHTML ='<%= l(:field_company_field) %>';
		  $('#first_name label').get(0).innerHTML='<%= l(:field_company_name) %>' + '<span class="required"> *</span>';

		} else {
		  $('#person_data').show();
		 	$('#job_title label').get(0).innerHTML ='<%= l(:field_contact_job_title) %>';
		  $('#first_name label').get(0).innerHTML='<%= l(:field_contact_first_name) %>' + '<span class="required"> *</span>';
		}

	}
</script>

	<p class="avatar extended" id="watchers">
		<%= avatar_to(@contact, :size => "64", :style => "vertical-align: middle;") %>
		<%= link_to image_tag('delete.png'), {:controller => 'attachments', :action => 'destroy', :id => @contact.avatar},
	                                         :confirm => l(:text_are_you_sure),
	                                         :method => :delete,
	                                         :class => 'delete',
											 :style => "vertical-align: middle;",
	                                         :title => l(:button_delete) unless @contact.avatar.blank? %>
	</p>
	<p class="extended"><%= label_tag l(:field_contact_avatar) %> <%= file_field_tag 'contact_avatar[file]', :size => 30, :id => nil  -%> </p>
	<p><%= f.check_box(:is_company, :label => l(:field_contact_is_company), :onclick => "togglePerson(this)" ) %></p>
	<p id="first_name"><%= f.text_field :first_name, :label => !@contact.is_company ? l(:field_contact_first_name) : l(:field_company_name), :required => true, :style => "width:90%;" %></p>
	<div id="person_data" style="<%= 'display: none;' if @contact.is_company  %>">

		<p><%= f.text_field :middle_name, :label=>l(:field_contact_middle_name) %></p>
		<p><%= f.text_field :last_name, :label=>l(:field_contact_last_name), :id => 'contact_last_name' %></p>
		<p><%= f.text_field :company, :label=>l(:field_contact_company) -%></p>
		<%= javascript_tag "observeAutocompleteField('contact_company', '#{escape_javascript auto_complete_companies_path}')" %>
		<p class="extended"><%= f.text_field :birthday, :size => 12 %><%= calendar_for('contact_birthday') %> </p>
	</div>
	<p id="job_title"><%= f.text_field :job_title, :label => !@contact.is_company ? l(:field_contact_job_title) : l(:field_company_field) %></p>
	<% @contact.build_address if @contact.address.blank? %>
	<%= f.fields_for(:address) do |a| %>
		<span class="extended">
		<%= render :partial => 'common/address_form', :locals => {:f => a} %>
		</span>

	<% end %>

	<div id="phones_fields">
		<p>
			<%= f.text_field :phone, :label=>l(:field_contact_phone), :style => "width:90%;" -%>
			<br>
			<em class="info"><%= l(:text_comma_separated) %></em>
		 </p>
	</div>

	<p>
		<%= f.text_field 'email', :label=>l(:field_contact_email), :style => "width:90%;" -%>
		<br>
		<em class="info"><%= l(:text_comma_separated) %></em>
	</p>

	<p class="extended"><%= f.text_field 'website', :label=>l(:field_contact_website) -%></p>
	<p class="extended"><%= f.text_field 'skype_name', :label=>l(:field_contact_skype) -%></p>
	<p class="extended notes"><%= f.text_area :background , :cols => 80, :rows => 8, :class => 'wiki-edit', :label=>l(:field_contact_background)  %></p>
	<%= wikitoolbar_for 'contact_background' %>

	<p class="extended">
		<%= label_tag l(:label_crm_tags_plural) %>
		<%= render :partial => "contacts_tags/tags_form" %>
	</p>

  <% if @project %>
		<p class="extended"><%= f.select :assigned_to_id, (@project.assignable_users.collect {|m| [m.name, m.id]}), :include_blank => true, :label => l(:label_crm_assigned_to) %></p>
	<% end %>

	<p class="extended"><%= f.select :visibility, collection_for_visibility_select, :include_blank => false, :label => l(:label_crm_contacts_visibility) %></p>

	<p id="show_details_link" style="display: none;"><%= link_to l(:label_crm_show_details), "#", :onclick => "$('#contact_data .extended').show();" %></p>

</div>

.srv/docker/redmine/redmine/plugins/redmine_contacts/app/views/contacts/_form_tags.html.erb
<div id="tags_data">
<%= tag_links(@contact.tag_list) %>
<% if authorize_for('contacts', 'update') %>
  <span class="contextual">
    <%= link_to l(:label_crm_edit_tags), {}, :onclick => "$('#edit_tags_form').show(); $('#tags_data').hide();  return false;", :id => 'edit_tags_link' %>
  </span>
<% end %>
</div>

<div id="edit_tags_form" style="display:none;">
  <%= form_tag( {:controller => 'contacts',
                :action => 'update',
                :project_id => @project,
                :id => @contact },
                :method => :put,
            	  :multipart => true ) do %>


  	<%= render :partial => "contacts_tags/tags_form" %>

  	<%= submit_tag l(:button_save), :class => "button-small" %>
  	<%= link_to l(:button_cancel), {}, :onclick => "$('#edit_tags_form').hide(); $('#tags_data').show(); return false;" %>
  <% end %>
</div>

.srv/docker/redmine/redmine/plugins/redmine_contacts/app/views/contacts/_name_observer.html.erb
<script type="text/javascript">
	jQuery(function($) {
      // when the #search field changes
      var duplicates = function() {
        var form = $("#contact_form"); // grab the form wrapping the search bar.
        var url = '<%= escape_javascript(url_for({:controller => "contacts_duplicates", :action => "duplicates", :project_id => @project, :contact_id => @contact})) %>';
        var formData = form.serialize();
        $.get(url, formData, function(data) { // perform an AJAX get, the trailing function is what happens on successful get.
            $("#duplicates").html(data); // replace the "results" div with the result of action taken
        });
      }

      $("#contact_first_name").observe_field(2, duplicates);
      $("#contact_middle_name").observe_field(2, duplicates);
      $("#contact_last_name").observe_field(2, duplicates);

    });
</script>


<%# observe_field("contact_first_name",
					:frequency => 1,
					:update => 'duplicates',
					:url => {:controller => 'contacts_duplicates', :action => 'duplicates', :project_id => @project, :contact_id => @contact},
					:with => "$('contact_form').serialize()") %>

<%# observe_field("contact_middle_name",
					:frequency => 1,
					:update => 'duplicates',
					:url => {:controller => 'contacts_duplicates', :action => 'duplicates', :project_id => @project, :contact_id => @contact},
					:with => "$('contact_form').serialize()") %>

<%# observe_field("contact_last_name",
					:frequency => 1,
					:update => 'duplicates',
					:url => {:controller => 'contacts_duplicates', :action => 'duplicates', :project_id => @project, :contact_id => @contact},
					:with => "$('contact_form').serialize()") %>

.srv/docker/redmine/redmine/plugins/redmine_contacts/app/views/contacts/_tag_list.html.erb
<div id="tags_data">
	<span class="tags">
		<%= render :partial => 'contacts/tags_item', :collection => tag_list, :locals => {:is_note => false} %>
	</span>
	<% if editable && authorize_for('contacts', 'update') %>
	<span class="contextual">
		<%= link_to l(:label_crm_edit_tags), {}, :onclick => "$('#edit_tags_form').show(); $('#tags_data').hide();  return false;", :id => 'edit_tags_link' %>
	</span>
	<% end %>
</div>

.srv/docker/redmine/redmine/plugins/redmine_contacts/app/views/contacts/_tags_cloud.html.erb
<div id="tags">
	<span id="single_tags">
		<h3><%= l(:label_crm_tags_plural) %></h3>
     <span class="tag_list"><%= tags_cloud.map{|tag| tag_link(tag.name, :count => tag.count)}.join(' ').html_safe %></span>
	</span>

</div>

.srv/docker/redmine/redmine/plugins/redmine_contacts/app/views/contacts/_upgrade_to_pro.html.erb
<h3><%= l(:label_crm_light_free_version) %></h3>
<ul>
  <li><%= link_to l(:label_crm_link_to_pro), "http://www.redminecrm.com/projects/crm/pages/last?from=light_upgrade" %>
  </li>
  <li><%= link_to l(:label_crm_link_to_pro_demo), "http://demo.redminecrm.com/projects/contacts-plugin/contacts?from=light_live_preview" %>
  </li>
  <li><%= link_to l(:label_crm_link_to_more_plugins), "http://www.redminecrm.com/pages/plugins?from=light_more_plugins" %>
  </li>
</ul>


.srv/docker/redmine/redmine/plugins/redmine_contacts/app/views/contacts/contacts_notes.html.erb
<div class="filters">
<% if !@tag %>

	<%= form_tag(params, :id => "query_form", :method => :get) do %>
	<%= hidden_field_tag('project_id', @project.to_param) if @project %>
	<h2>
		<span class="scope_title">
			<%= l(:label_crm_contact_all_note_plural) %>
		</span>
		<span class="live_search">
		 	<%= text_field_tag(:search_note, params[:search_note], :autocomplete => "off", :class => "live_search_field", :placeholder => l(:label_crm_contact_search) ) %>

        <script type="text/javascript">
           jQuery(function($) {
              // when the #search field changes
              $("#search_note").observe_field(2, function() {
                var form = $("#query_form"); // grab the form wrapping the search bar.
                var url = form.attr("action");
                var formData = form.serialize();
                $.get(url, formData, function(data) { // perform an AJAX get, the trailing function is what happens on successful get.
                    $("#contacts_notes").html(data); // replace the "results" div with the result of action taken
                });
              });
            });
        </script>

		</span>
	</h2>


	<% end %>



<% else %>
<h2 class="scope_title"><%= "#{l(:label_crm_contact_tag)}(#{@notes_pages.item_count}): #{tag_links(@tag)}".html_safe  %> </h2>
<% end %>
</div>

<div id="contacts_notes">
	<%= render :partial => 'notes/notes_list' %>
</div>

<% other_formats_links do |f| %>
	<%= f.link_to 'Atom', :url => params.merge(:key => User.current.rss_key) %>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'common/sidebar' %>

	<h3><%= l(:label_crm_note_plural) %></h3>
  <div id="note_types">
    <% collection_for_note_types_select.each do |note_type| %>
      <%= radio_button_tag "note_type", note_type[1], params[:type_id].to_s == note_type[1].to_s,  {:onchange => "document.location='#{url_for(params.merge(:type_id => note_type[1]))}';", :id => "note_type_#{note_type[1]}" }%>
      <%= label_tag "note_type_#{note_type[1]}", note_type[0] %>
      <br>
    <% end %>
  </div>

  <h3><%= l(:label_crm_tags_plural) %></h3>

	<div id="tags">
    <span class="tag_list"><%= @tags.map{|tag| content_tag(:span, link_to(tag.name, {:controller => "contacts", :action => "contacts_notes", :project_id => @project, :tag => tag.name}), {:class => "tag-label-color"}.merge(RedmineContacts.settings[:monochrome_tags].to_i > 0 ? {} : {:style => "background-color: #{tag_color(tag.name)}"}))}.join(' ').html_safe %></span>
	</div>

	<%= render :partial => 'common/recently_viewed' %>

<% end %>

<% content_for(:header_tags) do %>
 	<%= javascript_include_tag :contacts, :plugin => 'redmine_contacts'  %>
	<%= stylesheet_link_tag :contacts_sidebar, :plugin => 'redmine_contacts' %>
<% end %>

.srv/docker/redmine/redmine/plugins/redmine_contacts/app/views/contacts/context_menu.html.erb
<ul>
    <%= call_hook(:view_contacts_context_menu_start, {:contacts => @contacts, :can => @can, :back => @back }) %>

    <% unless @contact.nil? %>
        <li><%= context_menu_link l(:button_edit), {:controller => 'contacts', :action => 'edit', :id => @contact, :project_id => @project}, :class => 'icon-edit', :disabled => !@can[:edit] %></li>
        <% if User.current.logged? %>
        <li><%= watcher_link(@contact, User.current) %></li>
        <% end %>

        <% if !@project.nil? %>
            <% if @contact.is_company? %>
            <li><%= context_menu_link l(:label_crm_add_contact), {:controller => 'contacts', :action => 'new', :project_id => @project, :contact => {:company => @contact.name}},
                                :class => 'icon-company-contact', :disabled => !@can[:create] %></li>
            <% end %>
        <% end %>
    <% else %>
    <% end %>

    <%= call_hook(:view_contacts_context_menu_before_delete, {:contacts => @contacts, :can => @can, :back => @back }) %>

     <li><%= context_menu_link l(:button_delete), {:controller => 'contacts', :action => 'bulk_destroy', :ids => @contacts.collect(&:id), :project_id => @project},
                            :method => :delete, :confirm => l(:text_are_you_sure), :class => 'icon-del', :disabled => !@can[:delete] %></li>
    <%= call_hook(:view_contacts_context_menu_end, {:contacts => @contacts, :can => @can, :back => @back }) %>
</ul>

.srv/docker/redmine/redmine/plugins/redmine_contacts/app/views/contacts/create.js.erb
hideModal();
<% field_id = params[:contact_field_name].to_s.gsub("[", "_").gsub("]", "") -%>
$('select#<%= field_id %>')
         .append($("<option></option>")
         .attr("value",'<%= @contact.id %>')
         .attr("selected",'selected')
         .text('<%= @contact.name %>'));
$('input#<%= field_id %>').val('<%= @contact.id %>');
$('#<%= field_id %>_selected_contact').text('<%= @contact.name %>');
$('#<%= field_id %>_selected_contact').show();
$('#<%= field_id %>_selected_contact').scrollTop( 0 );
$('input#<%= field_id %>').hide();
$('#<%= field_id %>_edit_link').show();

.srv/docker/redmine/redmine/plugins/redmine_contacts/app/views/contacts/edit.html.erb
<div class="contextual">
  <%= link_to_if_authorized l(:label_crm_merge_duplicate_plural),  {:controller => 'contacts_duplicates', :action => 'index', :project_id => @project, :contact_id => @contact}, :class => 'icon icon-merge' unless @contact.new_record? %>
</div>

<h2><%= l(:label_crm_contact_edit_information) %></h2>

<%= labelled_form_for :contact, @contact,
                             :url => {:action => 'update', :project_id => @project, :id => @contact},
                             :html => { :multipart => true, :method => :put, :id => "contact_form" } do |f|  %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= render :partial => 'name_observer' %>
  <%= submit_tag l(:button_save) -%>
<% end -%>

<% content_for :sidebar do %>
	<%= render :partial => 'common/sidebar' %>
	<%= render :partial => 'contacts_duplicates/duplicates' %>
  <div id="contact_projects">
	 <%= render :partial => 'contacts_projects/related' %>
  </div>
<% end %>

<% content_for :header_tags do %>
  <%= javascript_include_tag :contacts, :plugin => 'redmine_contacts'  %>
  <%= stylesheet_link_tag :contacts_sidebar, :plugin => 'redmine_contacts' %>
  <%= robot_exclusion_tag %>
<% end %>

.srv/docker/redmine/redmine/plugins/redmine_contacts/app/views/contacts/load_tab.js.erb
<%
    @tab = params[:tab_name]
    @partial = params[:partial]
%>
$('#tab-placeholder-<%= @tab %>').html("<%= j(render :partial => @partial) %>")

.srv/docker/redmine/redmine/plugins/redmine_contacts/app/views/contacts/new.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'contacts/new_modal') %>');
$('#ajax-modal #contact_data .extended').hide();
$('#ajax-modal #contact_data #show_details_link').show();
showModal('ajax-modal', '800px');