.srv/docker/redmine/redmine/plugins/redmine_people/config/routes.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2016 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :people do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email, :avatar
      post :bulk_edit, :bulk_update, :send_mails
      delete :bulk_destroy
    end
    member do
      delete :destroy_avatar
      get 'tabs/:tab' => 'people#show', :as => "tabs"
      get 'load_tab' => 'people#load_tab', :as => "load_tab"
      delete "remove_subordinate" => "people#remove_subordinate" , :as => "remove_subordinate"
    end
end

resources :departments do
  member do
    get :autocomplete_for_person
    post :add_people
    delete :remove_person
    get 'tabs/:tab' => 'departments#show', :as => "tabs"
    get 'load_tab' => 'departments#load_tab', :as => "load_tab"
  end
end

resources :people_settings do
  collection do
    get :autocomplete_for_user
  end
end

resources :people_queries

.srv/docker/redmine/redmine/plugins/redmine_people/app/controllers/people_mails_controller.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2016 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

class PeopleMailsController < ApplicationController
  unloadable


  def new
    @people = People.visible.where(:id => params[:ids]).reject{|c| c.email.blank?}
    raise ActiveRecord::RecordNotFound if @people.empty?
    if !@people.collect{|c| c.send_mail_allowed?}.inject{|memo,d| memo && d}
      deny_access
      return
    end     
  end

  def create
    people = Contact.visible.where(:id => params[:ids])
    raise ActiveRecord::RecordNotFound if people.empty?
    if !people.collect{|c| c.send_mail_allowed?}.inject{|memo,d| memo && d}
      deny_access 
      return
    end  
    raise_delivery_errors = ActionMailer::Base.raise_delivery_errors
    # Force ActionMailer to raise delivery errors so we can catch it
    ActionMailer::Base.raise_delivery_errors = true
    delivered_people = []
    error_people = []
    people.each do |contact|
      begin  
        params[:message] = mail_macro(contact, params[:"message-content"])
        ContactsMailer.bulk_mail(contact, params).deliver
        delivered_people << contact

        note = ContactNote.new
        note.subject = params[:subject]
        note.content = params[:message]
        note.author = User.current   
        note.type_id = Note.note_types[:email]
        contact.notes << note   
        Attachment.attach_files(note, params[:attachments])    
        render_attachment_warning_if_needed(note) 
        
      rescue Exception => e
        error_people << [contact, e.message]
      end
      flash[:notice] = l(:notice_email_sent, delivered_people.map{|c| "#{c.name} <span class='icon icon-email'>#{c.emails.first}</span>"}.join(', ')).chomp[0,500] if delivered_people.any?
      flash[:error] = l(:notice_email_error, error_people.map{|e| "#{e[0].name}: #{e[1]}"}.join(', ')).chomp[0,500] if error_people.any?
    end
    
    ActionMailer::Base.raise_delivery_errors = raise_delivery_errors
    redirect_back_or_default({:controller => 'people', :action => 'index', :project_id => @project})
  end  

  def preview_email
    @text = mail_macro(Contact.visible.where(:id  => params[:ids][0]).first, params[:"message-content"])
    render :partial => 'common/preview'
  end  
end

.srv/docker/redmine/redmine/plugins/redmine_people/app/helpers/people_mails_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2016 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

module PeopleMailsHelper
end

.srv/docker/redmine/redmine/plugins/redmine_people/app/views/people_mails/new.html.erb
<h2><%= l(:label_people_new_mail) %></h2>


<div class="box" id="duplicates">
  <ul>
      <% @people.each do |person| %>
    <li>
      <%= avatar person, :size => "16" %>
      <%= link_to person.name, person_path(person) %>
      <%= "(#{person.job_title}) " unless person.job_title.blank? %>
      - <%= person.emails.first %>
        </li>
    <% end %>
  </ul>
</div>


<%= form_for(:email_message, :url => {:action => 'send_mails', :project_id => @project}, :html => {:multipart => true, :id => 'message-form'}) do %>
<%= @people.collect {|i| hidden_field_tag('ids[]', i.id)}.join.html_safe %>

<div class="box tabular">
  <p>
    <label><%= l(:field_mail_from) %></label>
    <%= text_field_tag('from', "#{User.current.name} <#{User.current.mail}>", :style => "width: 98%;") %>
    <%= link_to "#{l(:label_people_cc)}/#{l(:label_people_bcc)}", '#' , :onclick => "$('#mail_cc').show();$(this).hide();" %>
  </p>

<span id="mail_cc" style="display:none;">
  <p>
    <label><%= l(:label_people_cc) %></label>
    <%= text_field_tag('cc', '', :style => "width: 98%;") %>
  </p>

  <p>
    <label><%= l(:label_people_bcc) %></label>
    <%= text_field_tag('bcc', '', :style => "width: 98%;") %>
  </p>
</span>
  <p>
    <label><%= l(:field_subject) %></label>
    <%= text_field_tag('subject', '', :id => "subject", :style => "width: 98%;") %>
  </p>
  <p>
    <label><%= l(:field_message) %></label>
  <%= text_area_tag 'message-content', '', :cols => 60, :rows => 10, :class => 'wiki-edit' %>
  <em class="info"><%= l(:text_email_macros, :macro => "%%NAME%%, %%LAST_NAME%%, %%MIDDLE_NAME%%, %%FULL_NAME%%, %%COMPANY%%, %%DATE%%, %%[Custom field]%%") %></em>
  </p>
  <%= wikitoolbar_for 'message-content' %>

  <p id="attachments_form"><%= label_tag('attachments[1][file]', l(:label_attachment_plural))%><%= render :partial => 'attachments/form' %></p>
</div>

<p>
  <%= submit_tag l(:button_submit) %>
  <%= preview_link({ :controller => 'people', :action => 'preview_email' }, 'message-form') %>
</p>

<% end %>

<div id="preview" class="wiki"></div>

<% content_for :header_tags do %>
  <%= javascript_include_tag :redmine_people, :plugin => 'redmine_people'  %>
<% end %>